version: "2"
services:
    web:
        build: .
        volumes:
            - .:/app
        expose:
            - 80
        ports:
            - "80:80"
            - "443:443"
        environment:
            GITHUB_TOKEN:
            DATABASE_NAME: magento2
            DATABASE_USER: magento2
            DATABASE_PASSWORD: magento2
            DATABASE_ROOT_PASSWORD: magentoroot
            MAGENTO_MODE: developer
            PRODUCTION_ENVIRONMENT: 'false'
            APP_HOSTNAME: demo-magento2.docker
            PUBLIC_ADDRESS: https://demo-magento2.docker/

    varnish:
        image: quay.io/continuouspipe/magento2-varnish4:stable

    database:
        image: quay.io/continuouspipe/mysql5.7:stable
        environment:
            MYSQL_ROOT_PASSWORD: magentoroot
            MYSQL_DATABASE: magento2
            MYSQL_USER: magento2
            MYSQL_PASSWORD: magento2

    redis:
        image: quay.io/continuouspipe/redis3:stable
