version: '2'

services:
  proxy:
    image: quay.io/continuouspipe/nginx-reverse-proxy:stable
    environment:
      PROXY_LOCATIONS: '[{"location": "/", "backend": "http://varnish", "preserve_host": true}]'
      DNSDOCK_ALIAS: demo-magento2.docker
    ports:
      - "80:80"
      - "443:443"

  varnish:
    image: quay.io/continuouspipe/magento2-varnish4:stable
    environment:
      VARNISH_BACKEND_HOST: web
      VARNISH_BACKEND_PORT: 80

  web:
    build:
      context: .
      args: &WEB_BUILD_VARS
        GITHUB_TOKEN:
        MAGENTO_USERNAME:
        MAGENTO_PASSWORD:
    volumes:
      - .:/app
    environment: &WEB_ENV_VARS
      GITHUB_TOKEN:
      MAGENTO_USERNAME:
      MAGENTO_PASSWORD:
      WEB_HTTPS: "false"
      WEB_HTTPS_OFFLOADED: "true"
      WEB_REVERSE_PROXIED: "true"
      APP_HOSTNAME: demo-magento2.docker
      PUBLIC_ADDRESS: https://demo-magento2.docker/
      APP_USER_LOCAL: "true"
      DATABASE_HOST: database
      DATABASE_NAME: magento2
      DATABASE_USER: magento2
      DATABASE_PASSWORD: magento2
      DATABASE_ROOT_PASSWORD: magentoroot
      MAGENTO_CRYPT_KEY: "/x0NmcKk7BqKGX1h9JdHb7FcCaP74+bt"
      MAGENTO_MODE: developer
      PRODUCTION_ENVIRONMENT: 'false'

  database:
    image: quay.io/continuouspipe/mysql5.7:stable
    environment:
      MYSQL_ROOT_PASSWORD: magentoroot
      MYSQL_DATABASE: magento2
      MYSQL_USER: magento2
      MYSQL_PASSWORD: magento2

  redis:
    image: quay.io/continuouspipe/redis3:stable
